# Generated by Django 4.1.3 on 2022-12-01 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_post_post_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Category_slug',
            new_name='category_slug',
        ),
    ]
